### ISSUE TITLE
Add an API Call from the GK when a new test package is uploaded to the catalogue

### ISSUE THREAD

**Issue by mtouloup** [sonata-nfv/tng-vnv-dsm#7]
@jbonnet  Here is the end point of the tng-vnv-dsm for adding a new user/item (User/Test-Tag) pair for recommendation purposes.

curl -X POST http://pre-int-vnv-bcn.5gtango.eu:4010/tng-vnv-dsm/api/v1/users/items/"package-uuid"

**Comment by jbonnet** [comment]
@mtouloup what is the expected body on that POST? And return codes? 200, 201? 400, 404, ...?

**Comment by mtouloup** [comment]
@jbonnet 

Possible Responses:
1) Status Code: 201, Body: {"Response": "User-Item Added in the Dataset"}
2) Status Code: 404, Body: {"Response":"No test tags were found in the test decriptor"}
3) When an exception occurs--> Status Code: 500, Body: {"Response":"An error Occurred"}

I will also create a swagger file describing all the other end points as well.

**Comment by mtouloup** [comment]
@jbonnet 

Here is the swagger i promised! 

http://pre-int-vnv-bcn.5gtango.eu:4010/tng-vnv-dsm/api/v1/

**Comment by jbonnet** [comment]
Sorry, @mtouloup, I've forgoten about this...
Doubts:

1. why do we need a `.../delete/...` in the URL to `DELETE` and association?
1. `GET /health` and `GET /test_items` are to be ignored?
1. which users does `GET /users` return?
1. For every successful package uploading the GK should `POST /users/items/{package_uuid}`?
1. what does this `GET /users/{user}` get?
1. what's the difference from this `POST /users/{user}/{item}` compared to the above `POST /users/items/{package_uuid}`?

**Comment by mtouloup** [comment]
Hello @jbonnet 

I'm replying line by line :P

1) We dont! I will fix that
2) Yes, they are just for debugging purposes
3) Retrieves the users that the rec engine is trained for (users that uploaded a package with testing tags or users that execture specific tests-testing tags) - Also to be ignored...
4) Yes!
5) It gets the recommendations for the provided in the url user (currently logged int user)
6) The recommendation engine is learning how to recommend tests by two ways: 1) When a user uploads a test (eg Marios uploaded a package with testing tag X) 2) Jose chose and executed tests X,Y (/users/{user}/{item}). When Marios visits again the portal it should be recommended to him test tag Y
So, /users/{user}/{item} is giving the users activity to the recommendation engine

P.s The GK should only take care the No. 4 

Thanks!

**Comment by jbonnet** [comment]
Ok, @mtouloup 
> The GK should only take care the No. 4

4. For every successful package uploading the GK should POST /users/items/{package_uuid}

How do you wante the `package_uuid`, in the URL as shown (not very common) or in the body of the `POST` (more standard)?

**Comment by mtouloup** [comment]
In the URL since it is implemented that way... :D

**Comment by jbonnet** [comment]
@mtouloup there's a small problem: 

> ...when a new test package is uploaded to the catalogue

what happens if the package has only services?

**Comment by mtouloup** [comment]
Developed and tested.
